### ISSUE TITLE
AI needs to be implemented on the page

### ISSUE THREAD

**Issue by dillonKilroy** [COSC481W-2021Winter/capstone-project-mohcamanagement#108]
Right now we have the schedule AI working in python but now we have to figure out a  way to get it connected to our php in order for the AI to generate a schedule for the manager.

- [x] Allow for the webpage to access the AI
- [x] Display AI output to webpage
- [x] Debug AI and fix any issues
- [x] Prevent users being put on multiple shifts a day

**Comment by sjiang1** [comment]
If the manager clicks "generate" button, the schedule generation page will show a generated schedule.
