### ISSUE TITLE
Refactor User Creation Page

### ISSUE THREAD

**Issue by dillonKilroy** [COSC481W-2021Winter/capstone-project-mohcamanagement#109]
Clean up the page and code
- [x] Split PHP and HTML
- [x] Polish the form for updating/deleting users (so that it's user friendly)
- [x] Prevent the user from deleting themselves

**Comment by sjiang1** [comment]
- [ ] Split php and html
- [ ] Polish the form for updating/deleting users (so that it's user friendly)
- [ ] Prevent the user from deleting themselves

**Comment by HussainMohsin** [comment]
Combined @sjiang1 with our comment and completed all the tasks in the issue
