### ISSUE TITLE
Show write-offs on admin page

### ISSUE THREAD

**Issue by Bstaton321** [COSC481W-2021Winter/capstone-project-mohcamanagement#120]
- [x] As a manager I would like to see what items my employees write off so that it makes it easier for me to take inventory.

**Comment by sjiang1** [comment]
(optional) on the admin page, we also need a button for each write off so that the manager can check if a write off is seen.

> add a column in the database (write-offs) which indicate whether the manager has seen the write-offs. If the column is set to true, then the website no long show the write-offs.

**Comment by HussainMohsin** [comment]
All done
