### ISSUE TITLE
Tests for Inventory Log Page

### ISSUE THREAD

**Issue by dillonKilroy** [COSC481W-2021Winter/capstone-project-mohcamanagement#46]
Write acceptance test for the page.

Jessy writes tests:
- [x] Test to see if there is a default in the the drop-down menu
- [x] Test to see if you can add different types in the drop-down menu
- [x] Test the drop-down menu of adding inventory type to to the add item form

Douha writes tests:
<s>Test to see if page updates when choosing a different item in the drop-down menu</s>
- [x]  Test to see if there are entries in the drop-down menu

**Comment by jpoeana1** [comment]
- [ ] Test to see if page updates when choosing a different item
- [ ] Test to see if there are entries in the drop-down menu
- [ ] Test to see if there is a default in the the drop-downs
- [ ] Test to see you can add different types in the drop-down menu
