### ISSUE TITLE
Create Tests for the Update Availability Page

### ISSUE THREAD

**Issue by dillonKilroy** [COSC481W-2021Winter/capstone-project-mohcamanagement#47]
Write acceptance tests for this page.

- [x] Check that shift times are displayed on the table
- [x] Test to see if the check boxes and drop down work
- [x] Test to see if availability was updated (through database) and shown to user

- [x] Test to see if you select "off" the other shifts for that day are removed
- [x] Text for any bugs or errors
- [x] test to see if you get an error message if you don't select a day
- [x] test to see if you get an error message if you don't select a shift
- [x] test to see if when you click a shift and "off" simultaneously, it updates that day as "off"

**Comment by AdhamOudeif** [comment]
- [ ] Check that shift times are displayed on the table
- [ ] Test to see if the check boxes work
- [ ] Test database by seeing is user availability table was updated

**Comment by HussainMohsin** [comment]
- [ ] Test to see if you select "off" the other shifts for that day are removed
- [ ] Text for any bugs or errors
- [ ] test to see if you get an error message if you don't select a day
- [ ] test to see if you get an error message if you don't select a shift

**Comment by AdhamOudeif** [comment]
Hussain and I completed and tested all situations aforementioned in the trello board and added a test
