### ISSUE TITLE
Set up an editable schedule for the manager

### ISSUE THREAD

**Issue by Bstaton321** [COSC481W-2021Winter/capstone-project-mohcamanagement#63]
As a manager, I want to be able to edit the schedule for my employee's so that they will all be able to know when they are supposed to work during the week. The editable schedule will only reflect the schedule for next week instead of the current week.
- [x]  Add another table to handle the working schedule.
- [x]  Able to edit shift times database table.

**Comment by AdhamOudeif** [comment]
Done
