### ISSUE TITLE
Finalize Design

### ISSUE THREAD

**Issue by jpoeana1** [COSC481W-2021Winter/capstone-project-mohcamanagement#98]
This issue is a 2 week sprint. Not all tasks will be finished at the end of this week.

Generalizations _(Douha)_
- [x] Have a color scheme.
- [x] Choose text-font.
- [x] Get _specified_  pages looking good (i.e. format forms).
_Will write the pages Douha will be working on soon._

Start-up Page _(Jessica)_
- [x] Make footer look professional (i.e. Copyright tag).
- [x] Login/Logout should be in the navbar.
- [x] Display an image carousel on start page.
- [x] Display logo overlay.
- [x] Format page.

About Page _(Jessica)_
- [x] Format Page.

Login Page _(Jessica)_
- [x] Maybe move Registration link to Login as an option below the form- i.e. "New user" as a button or a word link.
- [x] Format Page.
- [x] Implement changes to userCheck page.

Company Register Page _(Jessica)_
- [x] Format page (similar to login form).

Admin Main and User Main pages _(Jessica)_
- [x] Implement navbar.
- [x] Format pages.

Schedule Generation _(Jessica)_
- [x] Make tables collapsible.
- [x] Format page.

Navbar _(Jessica)_
- [x] Have the navbar show up on each page.

Update Availability Page _(Jessica)_
- [x] Format tables.
- [x] Format Page.

**Comment by sjiang1** [comment]
By default: 

@douhaalemara will format the following pages:
Create User Page
- [ ] the form should be like the form on the login page

Item Inventory Page
- [ ] the form should be like the form on the login page (have the same color scheme)

Inventory Order Page
- [ ] the form should be like the form on the login page (have the same color scheme)

User Request Off Page
- [ ] prettier than the existing one (like the login page)

**Comment by douhaalemara** [comment]
Added background images to Create User Page, Item Inventory Page, Inventory Order Page, and User Request Off Page

Proper formats and center for Create user page 

Updated style fonts and formats and table for inventory order page and user request off page
